### ISSUE TITLE
Use `termion`.

### ISSUE THREAD

**Issue by ticki** [saschagrunert/rain#1]
Consider switching to [termion](https://github.com/ticki/termion) which is pure Rust.

**Comment by ticki** [comment]
I was planning on using this in [TFS](https://github.com/ticki/tfs), but can't when it has the dependencies it does.

PS: Your coding style is a lot like mine.

**Comment by saschagrunert** [comment]
Thank you very much for the feedback! I will have a look at it tomorrow. I am also open in implementing changes/features which make the integration easier for you.

**Comment by ticki** [comment]
It looks pretty good as-is, actually, but I'll let you know if I encounter issues.

Specifically, I think it would do nice for graphically tracking open files.

**Comment by saschagrunert** [comment]
So 57ffa4fe4142f6d41cbc944a4e6de46512f1592a should be fine I guess? :)

**Comment by ticki** [comment]
Nice!

**Comment by ticki** [comment]
Thanks a lot!!
